import { test } from 'node:test';
import { strict as assert } from 'node:assert';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { validate,run } from './worker.ts';
const task=(code=0)=>({id:'smoke',deliverable:'Smoke test',cwd:mkdtempSync(join(tmpdir(),'delivery-')),acceptance:['Check passes'],checks:[{command:process.execPath,args:['-e',`process.exit(${code})`]}]});
test('Reject incomplete contract',()=>assert.throws(()=>validate({id:'x'})));
test('Independent check passes simulation',()=>assert.equal(run(task(),true).status,'simulation_passed'));
test('Failed check prevents success',()=>assert.equal(run(task(1),true).status,'checks_failed'));
